services:
  worker:
    build:
      context: ./
      dockerfile: docker/worker/Dockerfile
    volumes:
      - ./backups:/var/backup/
  backend:
    build:
      context: ./
      dockerfile: docker/admin_backend/Dockerfile
    volumes:
      - ./backups:/var/backup/

