apiVersion: v1
kind: ConfigMap
metadata:
  name: tenant-config
  namespace: rfid-main
data:
  # SETTINGS
  SETTINGS_PATH: tenant.settings.base.Settings

  # SECRET
  PUBLIC_KEY: |
    -----BEGIN PUBLIC KEY-----
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEArNR+B9ahtbsYerULcvqz
    DOW1uzIkazUsr6oM03z5E/yEoxbLj/Wq9fUa64sPreeQ0HebBOOL5bD5zBbvh+GS
    qdsbLg6XRdMTIlo+qQFXUavOPHDvnVJvh3H8vKlYeEBA5Lw8Z7z5+Ph0lFmue6yh
    vxlry6LBJB3uabo0Ds1hc62hhdAnCZqu8kDfD9LnA/433wdf03Sgt/kjoXJ9fgUt
    LcYumEeVdv7AJXR7U0p46CQwdTL82w9dBVWfVmcsAcvae9hr6ENxVzRVyx+HV8Jk
    8LXL9Yh4N+H/HviRGOdBWfSQmlzh/FArG2izqEi4h6MnmctD0v7I1YAwtvoT8DCy
    5ri4Dy3Uz9n15eJ6DmEKE304zXPDQ2WaH2AlXxidl9Kichsrp4JsaAJLHOafyYPE
    c+1iRT+Sb2yNUsQDBJ6F5IkLzuewdHeVbWyuCoGxUZnQMGKfAUkNBEEnZiNzYPka
    Pwf+rHEecPoq51l8j9icF+t5IdxQNlXun4xuj4QwPl4MLJeVY1JtEGahspiEU1h4
    dQN1CLlBEmObZDoJuwzHKOK1aW/WLR/sRSHIf6KozcsmDG0kQtNfqgykDm0n9Vu9
    rc5b09aaBUO947BEK7tBS9xflC92NXclE7rIzgxv1rcWbC9udFUNYWgVZtLZbP1O
    JdshyHNA7X84mhM09YiKnU8CAwEAAQ==
    -----END PUBLIC KEY-----

  # TENANT
  TENANT_ID: "1"

  # AUTH API
  AUTH_API_HOST: http://auth:8000

  # ENV
  ENV_TYPE: dev

  # Logging
  LOG_LEVEL: DEBUG

  # POSTGRES
  POSTGRES_HOST: db
  POSTGRES_PORT: "5432"
  POSTGRES_DB: tenant
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

  # CORS
  ALLOWED_ORIGINS: "*"
  ALLOW_CREDENTIALS: "True"
  ALLOWED_METHODS: "*"
  ALLOWED_HEADERS: "*"

  # PATH
  ROOT_PATH: /tenant-api

  RABBIT_HOST: rabbit
  RABBIT_USERNAME: rfidio
  RABBIT_PASSWORD: rfidio

  # EXTERNAL
  NOTYFICATION_ATTEMPTS: "1,3"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tenant
  name: tenant
  namespace: rfid-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tenant
    spec:
      containers:
        - image: localhost:32000/rfidio-tenant:latest
          imagePullPolicy: Always
          name: tenant
          resources: {}
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db
                  key: POSTGRES_PASSWORD
          envFrom:
            - configMapRef:
                name: tenant-config
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tenant
  name: tenant
  namespace: rfid-main
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: tenant
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tenant-ingress
  namespace: rfid-main
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /tenant-api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: tenant
                port:
                  number: 8000
