apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-config
  namespace: "%NAMESPACE%"
data:
  PUBLIC_KEY: |
    -----BEGIN PUBLIC KEY-----
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA41Z9WXaplX+o5Szxf2pV
    2o7/dXDNwFoM7LJAdNno1pYYZUtph/5ickj3Pv6/MHmDIAg3bDmgKZyNC+mER7uz
    +J0jakNkKSjEbpNcDxq1WHBYBoGRZD2JNVpnTMimgCPpyl5tESFHHi1ro6Yw2F3G
    w2FWqK0EEoZLueGsSqizK1aIJM8ChJHoIcG5SZLy/QCBE1jlxUGkW4Ndho87TGWk
    JHXx+iP2+Y0bBHkBjE8WkhZovRxtbv3nO5kL6eTgzyRlsZ7VttKkng7XGmwQr5aw
    ZRE9L5HIvn5mznImBfS2SvTFaygs2E09SmbOAniQdqbxLgozBhaoeqXWyQgDmjX9
    xOlxbW7vHqOniGLXtSLeKY10brA6wMe4tq7v+x311a/IMKZpjuk6DwG4QnLFQnDc
    6WXZRwAZtSsheXpo5gykKGE+D1SA4P5enyMQLy2P65h+8PhhFdtEJFVt8go9LWf1
    mAQxZfSFdWXV+k4S2f8nwZifSjTCZGTocbHU6pPrnb8bphbK0HsVjSyFXL8EmkKm
    O8J8uPhWf1THpMv1gWUz1Fs0IJeKOde65yg6227o8wRrNaCTwOt476HLS4WEVpAU
    J3q8VzXSPIoQ4k0vDW6kkJuNtxr1tjX2rtBJjqFOFGGh3QcNuEPaZ0KNdvNCEzz7
    AGLRfWE6vgyE05eV7ie874ECAwEAAQ==
    -----END PUBLIC KEY-----

  BACKUP_DIR: /var/backup

  # ENV
  ENV_TYPE: dev
  INSIDE_CLUSTER: "True" 

  # Logging
  LOG_LEVEL: DEBUG

  #AUTH
  AUTH_API_HOST: http://auth:8000/v1
  TENANT_API_TEMPLATE: "http://{{ tenant_slug }}:8000"

  # POSTGRES
  POSTGRES_HOST: db
  POSTGRES_PORT: "5432"
  POSTGRES_DB: admin

  # CORS
  ALLOWED_ORIGINS: "*"
  ALLOW_CREDENTIALS: "True"
  ALLOWED_METHODS: "*"
  ALLOWED_HEADERS: "*"

  # PATH
  ROOT_PATH: /admin-api

  #MQ
  RABBIT_HOST: mq
  RABBIT_PORT: "5672"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rfid-bak
  namespace: "%NAMESPACE%"
spec:
  storageClassName: "%STORAGE_CLASS%"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: admin-api 
  name: admin 
  namespace: "%NAMESPACE%"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-api 
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: admin-api 
    spec:
      volumes:
        - name: bak-data
          persistentVolumeClaim:
            claimName: rfid-bak
      containers:
        - image: localhost:32000/rfidio-admin:latest 
          imagePullPolicy: Always
          name: admin-api
          resources: {}
          envFrom:
            - configMapRef:
                name: admin-config
          env:
            - name: NAMESPACE 
              value: "rfid-main"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db
                  key: POSTGRES_PASSWORD
            - name: RABBIT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbit
                  key: RABBIT_USER
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbit
                  key: RABBIT_PASSWORD
          ports:
            - containerPort: 8000
          volumeMounts:
          - name: bak-data
            mountPath: /var/backup
status: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-worker-config
  namespace: "%NAMESPACE%"
data:
  # Env
  ENV_TYPE: dev

  #Storage
  BACKUP_DIR: /var/backup

  # Logging
  LOG_LEVEL: DEBUG

  # Postgres
  POSTGRES_HOST: db
  POSTGRES_PORT: "5432"
  POSTGRES_DB: admin

  #MQ
  RABBIT_HOST: mq
  RABBIT_PORT: "5672"
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: admin-api 
  name: admin-api
  namespace: "%NAMESPACE%"
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: admin-api 
  type: LoadBalancer
status:
  loadBalancer: {}
