apiVersion: v1
kind: ServiceAccount
metadata:
  name: ghactions
  namespace: "%NAMESPACE%"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: "%NAMESPACE%"
  name: deploy-updater
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["update", "get", "patch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy-updater-binding
  namespace: "%NAMESPACE%"
subjects:
- kind: ServiceAccount
  name: ghactions
roleRef:
  kind: Role
  name: deploy-updater
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: "%NAMESPACE%"
  name: namespace-operator
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["ingress"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-operator-binding
  namespace: "%NAMESPACE%"
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: namespace-operator
  apiGroup: rbac.authorization.k8s.io
