apiVersion: v1
kind: ConfigMap
metadata:
  name: tenant-config
  namespace: rfid-main
data:
  # SETTINGS
  SETTINGS_PATH: tenant.settings.base.Settings

  # SECRET
  PUBLIC_KEY: |
    -----BEGIN PUBLIC KEY-----
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA41Z9WXaplX+o5Szxf2pV
    2o7/dXDNwFoM7LJAdNno1pYYZUtph/5ickj3Pv6/MHmDIAg3bDmgKZyNC+mER7uz
    +J0jakNkKSjEbpNcDxq1WHBYBoGRZD2JNVpnTMimgCPpyl5tESFHHi1ro6Yw2F3G
    w2FWqK0EEoZLueGsSqizK1aIJM8ChJHoIcG5SZLy/QCBE1jlxUGkW4Ndho87TGWk
    JHXx+iP2+Y0bBHkBjE8WkhZovRxtbv3nO5kL6eTgzyRlsZ7VttKkng7XGmwQr5aw
    ZRE9L5HIvn5mznImBfS2SvTFaygs2E09SmbOAniQdqbxLgozBhaoeqXWyQgDmjX9
    xOlxbW7vHqOniGLXtSLeKY10brA6wMe4tq7v+x311a/IMKZpjuk6DwG4QnLFQnDc
    6WXZRwAZtSsheXpo5gykKGE+D1SA4P5enyMQLy2P65h+8PhhFdtEJFVt8go9LWf1
    mAQxZfSFdWXV+k4S2f8nwZifSjTCZGTocbHU6pPrnb8bphbK0HsVjSyFXL8EmkKm
    O8J8uPhWf1THpMv1gWUz1Fs0IJeKOde65yg6227o8wRrNaCTwOt476HLS4WEVpAU
    J3q8VzXSPIoQ4k0vDW6kkJuNtxr1tjX2rtBJjqFOFGGh3QcNuEPaZ0KNdvNCEzz7
    AGLRfWE6vgyE05eV7ie874ECAwEAAQ==
    -----END PUBLIC KEY-----

  # TENANT

  # AUTH API
  AUTH_API_HOST: http://auth:8000

  # ENV
  ENV_TYPE: dev

  # Logging
  LOG_LEVEL: DEBUG

  # POSTGRES
  POSTGRES_HOST: db
  POSTGRES_PORT: "5432"

  # CORS
  ALLOWED_ORIGINS: "*"
  ALLOW_CREDENTIALS: "True"
  ALLOWED_METHODS: "*"
  ALLOWED_HEADERS: "*"

  # PATH
  ROOT_PATH: /tenant-api

  RABBIT_HOST: mq

  # EXTERNAL
  NOTYFICATION_ATTEMPTS: "1,3"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tenant
  name: tenant
  namespace: rfid-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tenant
    spec:
      containers:
        - image: localhost:32000/rfidio-tenant:latest
          imagePullPolicy: Always
          name: tenant
          resources: {}
          ports:
            - containerPort: 8000
          env:
            - name:
                key: POSTGRES_DB
                value: "tenant"
            - name:
                key: TENANT_ID
                value: "1"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db
                  key: POSTGRES_PASSWORD
            - name: RABBIT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbit
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbit
                  key: RABBITMQ_DEFAULT_PASS
          envFrom:
            - configMapRef:
                name: tenant-config
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tenant
  name: tenant
  namespace: rfid-main
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: tenant
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tenant-ingress
  namespace: rfid-main
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /tenant-api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: tenant
                port:
                  number: 8000
