[tool.poetry]
name = "deploy"
version = "0.1.0"
description = ""
authors = ["Roland Sobczak <rolandsobczak@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
kubernetes = "^30.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
