name: ci

on:
  push:
    branches:
      - main
      - develop

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: ${{ vars.REGISTRY_HOST }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/backend/Dockerfile
          push: true
          tags: |
            ${{ vars.REGISTRY_HOST }}/rfid-admin/rfid-admin-api:latest
            ${{ vars.REGISTRY_HOST }}/rfid-admin/rfid-admin-api:${{ github.sha }}
