name: "Deploy admin API"
on:
  push:
    branches:
      - main
      - develop

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: ${{ vars.REGISTRY_HOST }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/backend/Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKER_REPO }}/rfid-admin-api:latest
            ${{ vars.DOCKER_REPO }}/rfid-admin-api:${{ github.sha }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/worker/Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKER_REPO }}/rfid-backup-worker:latest
            ${{ vars.DOCKER_REPO }}/rfid-backup-worker:${{ github.sha }}
      - 
        name: kube admin update
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: set image deployments --namespace=${{ vars.NAMESPACE }} --selector="app=admin-api" admin-api=${{ vars.DOCKER_REPO }}/rfid-admin-api:${{ github.sha }}
